CREATE DATABASE IF NOT EXISTS news_web CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE news_web;

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  slug VARCHAR(160) NOT NULL UNIQUE,
  name_hi VARCHAR(160) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE articles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(180) NOT NULL UNIQUE,
  title_en VARCHAR(255) NOT NULL,
  title_hi VARCHAR(255) NULL,
  excerpt_en TEXT NULL,
  excerpt_hi TEXT NULL,
  content_en LONGTEXT NOT NULL,
  content_hi LONGTEXT NULL,
  author_name VARCHAR(120) NOT NULL,
  hero_image VARCHAR(255) NULL,
  video_url VARCHAR(255) NULL,
  language_primary VARCHAR(30) NOT NULL DEFAULT 'English',
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  published_at DATETIME NULL,
  category_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_articles_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE epapers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  edition_date DATETIME NOT NULL,
  language VARCHAR(30) NOT NULL DEFAULT 'English',
  pdf_url VARCHAR(255) NOT NULL,
  thumbnail_url VARCHAR(255) NOT NULL,
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE highlights (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title_en VARCHAR(255) NOT NULL,
  title_hi VARCHAR(255) NULL,
  summary_en TEXT NULL,
  summary_hi TEXT NULL,
  image_url LONGTEXT NULL,
  caption TEXT NULL,
  priority VARCHAR(30) NOT NULL DEFAULT 'NORMAL',
  priority_weight INT NOT NULL DEFAULT 1,
  location VARCHAR(180) NULL,
  tags VARCHAR(255) NULL,
  source VARCHAR(180) NULL,
  alt_text VARCHAR(255) NULL,
  views INT NOT NULL DEFAULT 0,
  downloads INT NOT NULL DEFAULT 0,
  shares INT NOT NULL DEFAULT 0,
  show_in_gallery BOOLEAN NOT NULL DEFAULT TRUE,
  allow_downloads BOOLEAN NOT NULL DEFAULT TRUE,
  allow_sharing BOOLEAN NOT NULL DEFAULT TRUE,
  add_watermark BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  category_id INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_highlights_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE nits (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  title_hi VARCHAR(255) NULL,
  summary TEXT NOT NULL,
  summary_hi TEXT NULL,
  region VARCHAR(120) NULL,
  tag VARCHAR(120) NULL,
  sentiment VARCHAR(30) NOT NULL DEFAULT 'NEUTRAL',
  priority VARCHAR(30) NOT NULL DEFAULT 'MEDIUM',
  source VARCHAR(120) NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  category_id INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_nits_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE inshorts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  headline_en VARCHAR(255) NOT NULL,
  headline_hi VARCHAR(255) NULL,
  body_en TEXT NOT NULL,
  body_hi TEXT NULL,
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  category_id INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_inshorts_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE notifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  audience VARCHAR(120) NULL,
  type VARCHAR(30) NOT NULL DEFAULT 'EDITORIAL',
  sent_at DATETIME NULL,
  is_scheduled BOOLEAN NOT NULL DEFAULT FALSE,
  scheduled_for DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
